// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh99_guvuryYODPhGo-qXG0jhg6oQyfR0',
    appId: '1:50445310603:web:19bd116f73b8826e13928e',
    messagingSenderId: '50445310603',
    projectId: 'kezel-adfac',
    authDomain: 'kezel-adfac.firebaseapp.com',
    storageBucket: 'kezel-adfac.appspot.com',
    measurementId: 'G-JWB2PF7095',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrixsFLCUbrMOd8jzBb5Fe_SrMJV4iR8',
    appId: '1:50445310603:android:d4d87eed0458bedc13928e',
    messagingSenderId: '50445310603',
    projectId: 'kezel-adfac',
    storageBucket: 'kezel-adfac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB608K-JgzmkNGkKHBFJEBFeRlzsKrR6W8',
    appId: '1:50445310603:ios:1e251cabcc2ebb3a13928e',
    messagingSenderId: '50445310603',
    projectId: 'kezel-adfac',
    storageBucket: 'kezel-adfac.appspot.com',
    iosBundleId: 'com.example.kezel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB608K-JgzmkNGkKHBFJEBFeRlzsKrR6W8',
    appId: '1:50445310603:ios:ca0f2c4db04b4b7313928e',
    messagingSenderId: '50445310603',
    projectId: 'kezel-adfac',
    storageBucket: 'kezel-adfac.appspot.com',
    iosBundleId: 'com.example.kezel.RunnerTests',
  );
}
